### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by osarrouy** [distributedgallery/chaos-machine#1]
- [x] Finish up `@chaos/core` tests
- [x] Publish `@chaos/core` npm package
- [x] Publish `@chaos/chaos.js` npm package
